In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/ventas_prueba.csv")

In [3]:
df

       cliente             producto   monto
0   Juan Perez  Persiana enrollable  250000
1  Maria Lopez     Cortina blackout  180000
2  Carlos Ruiz   Persiana veneciana  320000

In [4]:
df.head()

       cliente             producto   monto
0   Juan Perez  Persiana enrollable  250000
1  Maria Lopez     Cortina blackout  180000
2  Carlos Ruiz   Persiana veneciana  320000

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   cliente   3 non-null      str
 1   producto  3 non-null      str
 2   monto     3 non-null      int64
dtypes: int64(1), str(2)
memory usage: 204.0 bytes

In [6]:
df.describe()

          monto
count       3.0
mean   250000.0
std     70000.0
min    180000.0
25%    215000.0
50%    250000.0
75%    285000.0
max    320000.0

In [7]:
df.dtypes

cliente       str
producto      str
monto       int64
dtype: object

In [8]:
df.shape

(3, 3)

In [9]:
df.columns

Index(['cliente', 'producto', 'monto'], dtype='str')

In [10]:
df["monto"]

0    250000
1    180000
2    320000
Name: monto, dtype: int64

In [11]:
df[["cliente", "monto"]]

       cliente   monto
0   Juan Perez  250000
1  Maria Lopez  180000
2  Carlos Ruiz  320000

In [12]:
df.iloc[0]

cliente              Juan Perez
producto    Persiana enrollable
monto                    250000
Name: 0, dtype: object

In [13]:
df.iloc[2]

cliente            Carlos Ruiz
producto    Persiana veneciana
monto                   320000
Name: 2, dtype: object

In [14]:
df[df["monto"] > 200000]

       cliente             producto   monto
0   Juan Perez  Persiana enrollable  250000
2  Carlos Ruiz   Persiana veneciana  320000

In [15]:
  df["monto"] > 200000

0     True
1    False
2     True
Name: monto, dtype: bool

In [16]:
  df["monto"] < 200000

0    False
1     True
2    False
Name: monto, dtype: bool

In [18]:
df["cliente"] == "Juan Perez"

0    True
1    True
2    True
Name: cliente, dtype: bool

In [19]:
df[df["cliente"] == "Juan Perez"]

      cliente             producto   monto
0  Juan Perez  Persiana enrollable  250000
1  Juan Perez     Cortina blackout  180000
2  Juan Perez   Persiana veneciana  320000

In [20]:
df

      cliente             producto   monto
0  Juan Perez  Persiana enrollable  250000
1  Juan Perez     Cortina blackout  180000
2  Juan Perez   Persiana veneciana  320000

In [21]:
df_correcto = pd.DataFrame({
    "cliente": ["Juan Perez", "Maria Lopez", "Carlos Ruiz"],
    "producto": ["Persiana enrollable", "Cortina blackout", "Persiana veneciana"],
    "monto": [250000, 180000, 320000]
})

df_correcto.to_csv("../data/ventas_prueba.csv", index=False)

In [22]:
df = pd.read_csv("../data/ventas_prueba.csv")

In [23]:
df

       cliente             producto   monto
0   Juan Perez  Persiana enrollable  250000
1  Maria Lopez     Cortina blackout  180000
2  Carlos Ruiz   Persiana veneciana  320000

In [24]:
df[df["cliente"] == "Juan Perez"]

      cliente             producto   monto
0  Juan Perez  Persiana enrollable  250000

In [25]:
df["monto_con_iva"] = df["monto"] * 1.19

In [26]:
df

       cliente             producto   monto  monto_con_iva
0   Juan Perez  Persiana enrollable  250000       297500.0
1  Maria Lopez     Cortina blackout  180000       214200.0
2  Carlos Ruiz   Persiana veneciana  320000       380800.0

In [27]:
# La forma "manual" (fila por fila), como tendrías que hacerlo sin pandas
resultados = []
for monto in df["monto"]:
    resultados.append(monto * 1.19)
print(resultados)

[297500.0, 214200.0, 380800.0]

In [28]:
df.groupby("producto")["monto"].sum()

producto
Cortina blackout       180000
Persiana enrollable    250000
Persiana veneciana     320000
Name: monto, dtype: int64

In [29]:
df.groupby("cliente")["monto"].mean()

cliente
Carlos Ruiz    320000.0
Juan Perez     250000.0
Maria Lopez    180000.0
Name: monto, dtype: float64

In [30]:
df_extra = pd.concat([df, pd.DataFrame({
    "cliente": ["Juan Perez"],
    "producto": ["Persiana enrollable"],
    "monto": [250000],
    "monto_con_iva": [297500.0]
})], ignore_index=True)

df_extra.groupby("cliente")["monto"].sum()

cliente
Carlos Ruiz    320000
Juan Perez     500000
Maria Lopez    180000
Name: monto, dtype: int64