In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
df = pd.DataFrame({
    "cliente": ["Juan Perez", "Maria Lopez", "Carlos Ruiz", "Maria Lopez", None],
    "producto": ["Persiana enrollable", "Cortina blackout", None, "Cortina blackout", "Persiana veneciana"],
    "monto": ["250000", "180000", "320000", "180000", "150000"],
    "fecha": ["2026-09-01", "2026-09-02", "2026-09-03", "2026-09-02", None]
})

In [5]:
df

       cliente             producto   monto       fecha
0   Juan Perez  Persiana enrollable  250000  2026-09-01
1  Maria Lopez     Cortina blackout  180000  2026-09-02
2  Carlos Ruiz                  NaN  320000  2026-09-03
3  Maria Lopez     Cortina blackout  180000  2026-09-02
4          NaN   Persiana veneciana  150000         NaN

In [5]:
df.isnull()

   cliente  producto  monto  fecha
0    False     False  False  False
1    False     False  False  False
2    False      True  False  False
3    False     False  False  False
4     True     False  False   True

In [6]:
df.isnull().sum()

cliente     1
producto    1
monto       0
fecha       1
dtype: int64

In [7]:
df_sin_nulos = df.dropna()
df_sin_nulos

       cliente             producto   monto       fecha
0   Juan Perez  Persiana enrollable  250000  2026-09-01
1  Maria Lopez     Cortina blackout  180000  2026-09-02
3  Maria Lopez     Cortina blackout  180000  2026-09-02

In [8]:
df_relleno = df.fillna("Desconocido")
df_relleno

       cliente             producto   monto        fecha
0   Juan Perez  Persiana enrollable  250000   2026-09-01
1  Maria Lopez     Cortina blackout  180000   2026-09-02
2  Carlos Ruiz          Desconocido  320000   2026-09-03
3  Maria Lopez     Cortina blackout  180000   2026-09-02
4  Desconocido   Persiana veneciana  150000  Desconocido

In [9]:
df_decidido = df.dropna(subset=["cliente", "fecha"])
df_decidido

       cliente             producto   monto       fecha
0   Juan Perez  Persiana enrollable  250000  2026-09-01
1  Maria Lopez     Cortina blackout  180000  2026-09-02
2  Carlos Ruiz                  NaN  320000  2026-09-03
3  Maria Lopez     Cortina blackout  180000  2026-09-02

In [6]:
df.duplicated()

0    False
1    False
2    False
3     True
4    False
dtype: bool

In [7]:
df_sin_duplicados = df.drop_duplicates()
df_sin_duplicados

       cliente             producto   monto       fecha
0   Juan Perez  Persiana enrollable  250000  2026-09-01
1  Maria Lopez     Cortina blackout  180000  2026-09-02
2  Carlos Ruiz                  NaN  320000  2026-09-03
4          NaN   Persiana veneciana  150000         NaN

In [8]:
print(df.shape)
print(df_sin_duplicados.shape)

(5, 4)
(4, 4)

In [9]:
df = pd.DataFrame({
    "cliente": ["Juan Perez", "Maria Lopez", "Carlos Ruiz", "Maria Lopez", None],
    "producto": ["Persiana enrollable", "Cortina blackout", None, "Cortina blackout", "Persiana veneciana"],
    "monto": ["250000", "180000", "320000", "180000", "150000"],
    "fecha": ["2026-09-01", "2026-09-02", "2026-09-03", "2026-08-12", None]
})

In [10]:
df

       cliente             producto   monto       fecha
0   Juan Perez  Persiana enrollable  250000  2026-09-01
1  Maria Lopez     Cortina blackout  180000  2026-09-02
2  Carlos Ruiz                  NaN  320000  2026-09-03
3  Maria Lopez     Cortina blackout  180000  2026-08-12
4          NaN   Persiana veneciana  150000         NaN

In [11]:
df.drop_duplicates()

       cliente             producto   monto       fecha
0   Juan Perez  Persiana enrollable  250000  2026-09-01
1  Maria Lopez     Cortina blackout  180000  2026-09-02
2  Carlos Ruiz                  NaN  320000  2026-09-03
3  Maria Lopez     Cortina blackout  180000  2026-08-12
4          NaN   Persiana veneciana  150000         NaN

In [12]:
df.drop_duplicates(subset=["cliente", "producto", "monto"])

       cliente             producto   monto       fecha
0   Juan Perez  Persiana enrollable  250000  2026-09-01
1  Maria Lopez     Cortina blackout  180000  2026-09-02
2  Carlos Ruiz                  NaN  320000  2026-09-03
4          NaN   Persiana veneciana  150000         NaN

In [13]:
df.drop_duplicates(subset=["cliente"])

       cliente             producto   monto       fecha
0   Juan Perez  Persiana enrollable  250000  2026-09-01
1  Maria Lopez     Cortina blackout  180000  2026-09-02
2  Carlos Ruiz                  NaN  320000  2026-09-03
4          NaN   Persiana veneciana  150000         NaN

In [14]:
df.drop_duplicates(subset=["cliente", "producto", "monto", "fecha"])

       cliente             producto   monto       fecha
0   Juan Perez  Persiana enrollable  250000  2026-09-01
1  Maria Lopez     Cortina blackout  180000  2026-09-02
2  Carlos Ruiz                  NaN  320000  2026-09-03
3  Maria Lopez     Cortina blackout  180000  2026-08-12
4          NaN   Persiana veneciana  150000         NaN

In [15]:
df.dtypes

cliente     str
producto    str
monto       str
fecha       str
dtype: object

In [16]:
df["monto"] = df["monto"].astype(int)
df.dtypes

cliente       str
producto      str
monto       int64
fecha         str
dtype: object

In [17]:
df["monto"].sum()

np.int64(1080000)

In [18]:
df_limpio = (
    df
    .dropna(subset=["cliente", "fecha"])
    .drop_duplicates(subset=["cliente", "producto", "monto", "fecha"])
)
df_limpio["monto"] = df_limpio["monto"].astype(int)
df_limpio

       cliente             producto   monto       fecha
0   Juan Perez  Persiana enrollable  250000  2026-09-01
1  Maria Lopez     Cortina blackout  180000  2026-09-02
2  Carlos Ruiz                  NaN  320000  2026-09-03
3  Maria Lopez     Cortina blackout  180000  2026-08-12

In [19]:
df_limpio.shape
df_limpio.dtypes

cliente       str
producto      str
monto       int64
fecha         str
dtype: object